# Generated by Django 5.2.6 on 2025-11-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daromad", models.IntegerField()),
                ("yosh", models.IntegerField()),
                (
                    "kredit_tarixchasi",
                    models.CharField(
                        choices=[
                            ("Yaxshi", "Yaxshi"),
                            ("O'rtacha", "O'rtacha"),
                            ("Yomon", "Yomon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qarzlar", models.IntegerField()),
                ("kredit_miqdori", models.IntegerField()),
                ("natija", models.CharField(blank=True, max_length=50, null=True)),
                ("garov", models.CharField(blank=True, max_length=100, null=True)),
                ("ish_staji", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shartlar", models.JSONField()),
                ("natija", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qiymat", models.CharField(max_length=100)),
                ("key", models.IntegerField(unique=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qiymatlar",
                        to="decision.attribute",
                    ),
                ),
            ],
        ),
    ]
